export const DYNAMIC_PRESETS = {
  vtuber: {
    name: 'VTuber Pop',
    fontFamily: 'Bangers',
    fontSize: 88,
    bold: true,
    italic: false,
    uppercase: true,
    highlight: '#FFD700',
    textColor: '#FFFFFF',
    outlineColor: '#FF1493',
    shadowColor: '#000000',
    outline: 5,
    shadow: 4,
    glow: 12,
    glowColor: '#FFD700',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'pop-in',
    animSpeed: 180,
  },
  neon: {
    name: 'Neon Rave',
    fontFamily: 'Bebas Neue',
    fontSize: 82,
    bold: true,
    italic: false,
    uppercase: true,
    highlight: '#00FFFF',
    textColor: '#FF00FF',
    outlineColor: '#000000',
    shadowColor: '#001A26',
    outline: 2,
    shadow: 3,
    glow: 20,
    glowColor: '#00FFFF',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'fade-in',
    animSpeed: 270,
  },
  anime: {
    name: 'Anime Clash',
    fontFamily: 'Anton',
    fontSize: 92,
    bold: true,
    italic: true,
    uppercase: true,
    highlight: '#FF4444',
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#880000',
    outline: 7,
    shadow: 5,
    glow: 6,
    glowColor: '#FF4444',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'slide-up',
    animSpeed: 130,
  },
  clean: {
    name: 'Clean Pro',
    fontFamily: 'Montserrat',
    fontSize: 72,
    bold: true,
    italic: false,
    uppercase: false,
    highlight: '#FFD700',
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    outline: 3,
    shadow: 3,
    glow: 0,
    glowColor: '#FFD700',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'fade-in',
    animSpeed: 220,
  },
  retro: {
    name: 'Retro Game',
    fontFamily: 'Bungee',
    fontSize: 78,
    bold: true,
    italic: false,
    uppercase: true,
    highlight: '#FFD700',
    textColor: '#FF6B6B',
    outlineColor: '#2D0A4E',
    shadowColor: '#2D0A4E',
    outline: 5,
    shadow: 6,
    glow: 0,
    glowColor: '#FFD700',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'typewriter',
    animSpeed: 85,
  },
  idol: {
    name: 'Idol Vibes',
    fontFamily: 'Poppins',
    fontSize: 76,
    bold: true,
    italic: false,
    uppercase: false,
    highlight: '#FFB7DD',
    textColor: '#FFFFFF',
    outlineColor: '#FF69B4',
    shadowColor: '#CC3377',
    outline: 3,
    shadow: 3,
    glow: 16,
    glowColor: '#FFB7DD',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'pop-in',
    animSpeed: 165,
  },
  newsflash: {
    name: 'Newsflash',
    fontFamily: 'Impact',
    fontSize: 84,
    bold: true,
    italic: false,
    uppercase: true,
    highlight: '#FFFF00',
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#111111',
    outline: 5,
    shadow: 3,
    glow: 0,
    glowColor: '#FFFF00',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'typewriter',
    animSpeed: 75,
  },
  cybergold: {
    name: 'Cyber Gold',
    fontFamily: 'Bebas Neue',
    fontSize: 82,
    bold: true,
    italic: false,
    uppercase: true,
    highlight: '#FFD700',
    textColor: '#FFA500',
    outlineColor: '#1A0800',
    shadowColor: '#000000',
    outline: 3,
    shadow: 5,
    glow: 16,
    glowColor: '#FFD700',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'slide-up',
    animSpeed: 195,
  },
  horror: {
    name: 'Horror',
    fontFamily: 'Creepster',
    fontSize: 90,
    bold: true,
    italic: false,
    uppercase: true,
    highlight: '#00FF66',
    textColor: '#CC0000',
    outlineColor: '#000000',
    shadowColor: '#1A0000',
    outline: 5,
    shadow: 7,
    glow: 12,
    glowColor: '#00FF66',
    scale: 100,
    animation: 'color-only',
    groupAnimation: 'pop-in',
    animSpeed: 155,
  },
};
