export const EMOTION_PRESETS = {
  angry: {
    name: 'Angry',
    highlight_color: 'FF0000',
    normal_color: 'CC0000',
    outline_color: '000000',
    font_size_mult: 1.2,
    shake: true,
  },
  creepy: {
    name: 'Creepy',
    highlight_color: '00FF00',
    normal_color: '006600',
    outline_color: '000000',
    font_name: 'Creepster',
    font_size_mult: 1.1,
  },
  shy: {
    name: 'Shy',
    highlight_color: 'FFB6C1',
    normal_color: 'FFC0CB',
    outline_color: 'FF69B4',
    font_size_mult: 0.9,
  },
  gloomy: {
    name: 'Gloomy',
    highlight_color: '6B7B8C',
    normal_color: '4A5568',
    outline_color: '1A202C',
    font_size_mult: 0.95,
  },
  bright: {
    name: 'Bright',
    highlight_color: 'FFFF00',
    normal_color: 'FFF700',
    outline_color: 'FF8C00',
    font_size_mult: 1.15,
  },
  energetic: {
    name: 'Energetic',
    highlight_color: 'FF6600',
    normal_color: 'FFAA00',
    outline_color: 'FF0000',
    font_size_mult: 1.25,
  },
  obnoxious: {
    name: 'Obnoxious',
    highlight_color: 'FF00FF',
    normal_color: '00FFFF',
    outline_color: 'FFFF00',
    font_size_mult: 1.3,
    rainbow: true,
  },
  romantic: {
    name: 'Romantic',
    highlight_color: 'FF1493',
    normal_color: 'FF69B4',
    outline_color: 'C71585',
    font_size_mult: 1.05,
  },
};
