export const STATIC_PRESETS = {
  classic: {
    name: 'Classic',
    fontFamily: 'Arial Black',
    fontSize: 70,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    outline: 4,
    shadow: 2,
    glow: 0,
    glowColor: '#FFFFFF',
    sentenceAnimation: 'fade-in',
    animSpeed: 300,
  },
  cinematic: {
    name: 'Cinematic',
    fontFamily: 'Bebas Neue',
    fontSize: 65,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    outline: 2,
    shadow: 3,
    glow: 0,
    glowColor: '#FFFFFF',
    sentenceAnimation: 'fade-in',
    animSpeed: 400,
  },
  minimal: {
    name: 'Minimal',
    fontFamily: 'Montserrat',
    fontSize: 60,
    bold: true,
    italic: false,
    uppercase: false,
    textColor: '#FFFFFF',
    outlineColor: '#333333',
    shadowColor: '#000000',
    outline: 2,
    shadow: 1,
    glow: 0,
    glowColor: '#FFFFFF',
    sentenceAnimation: 'none',
    animSpeed: 200,
  },
  neonStatic: {
    name: 'Neon Glow',
    fontFamily: 'Bebas Neue',
    fontSize: 75,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#00FFFF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    outline: 2,
    shadow: 0,
    glow: 15,
    glowColor: '#00FFFF',
    sentenceAnimation: 'fade-in',
    animSpeed: 350,
  },
  retrostatic: {
    name: 'Retro VHS',
    fontFamily: 'Bungee',
    fontSize: 70,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#FF6B6B',
    outlineColor: '#2D0A4E',
    shadowColor: '#2D0A4E',
    outline: 4,
    shadow: 5,
    glow: 0,
    glowColor: '#FF6B6B',
    sentenceAnimation: 'slide-up',
    animSpeed: 250,
  },
  elegant: {
    name: 'Elegant',
    fontFamily: 'Poppins',
    fontSize: 65,
    bold: true,
    italic: true,
    uppercase: false,
    textColor: '#FFEFD5',
    outlineColor: '#2C1810',
    shadowColor: '#1A0F0A',
    outline: 3,
    shadow: 2,
    glow: 5,
    glowColor: '#FFD700',
    sentenceAnimation: 'fade-in',
    animSpeed: 400,
  },
};
