export const STATIC_PRESETS = {
  natural: {
    name: 'Natural',
    fontFamily: 'Montserrat',
    fontSize: 78,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    outline: 4,
    shadow: 2,
    glow: 10,
    glowColor: '#FFFFFF',
    sentenceAnimation: 'fade-in',
    animSpeed: 300,
  },
  classic: {
    name: 'Classic',
    fontFamily: 'Arial Black',
    fontSize: 72,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#111111',
    outline: 5,
    shadow: 3,
    glow: 0,
    glowColor: '#FFFFFF',
    sentenceAnimation: 'fade-in',
    animSpeed: 300,
  },
  cinematic: {
    name: 'Cinematic',
    fontFamily: 'Bebas Neue',
    fontSize: 68,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#111111',
    outline: 2,
    shadow: 6,
    glow: 0,
    glowColor: '#FFFFFF',
    sentenceAnimation: 'fade-in',
    animSpeed: 450,
  },
  minimal: {
    name: 'Minimal',
    fontFamily: 'Montserrat',
    fontSize: 62,
    bold: false,
    italic: false,
    uppercase: false,
    textColor: '#FFFFFF',
    outlineColor: '#222222',
    shadowColor: '#000000',
    outline: 2,
    shadow: 2,
    glow: 0,
    glowColor: '#FFFFFF',
    sentenceAnimation: 'none',
    animSpeed: 200,
  },
  neonStatic: {
    name: 'Neon Glow',
    fontFamily: 'Bebas Neue',
    fontSize: 78,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#00FFFF',
    outlineColor: '#000000',
    shadowColor: '#001A26',
    outline: 2,
    shadow: 3,
    glow: 20,
    glowColor: '#00FFFF',
    sentenceAnimation: 'fade-in',
    animSpeed: 320,
  },
  retrostatic: {
    name: 'Retro VHS',
    fontFamily: 'Bungee',
    fontSize: 72,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#FF6B6B',
    outlineColor: '#2D0A4E',
    shadowColor: '#2D0A4E',
    outline: 5,
    shadow: 6,
    glow: 0,
    glowColor: '#FF6B6B',
    sentenceAnimation: 'slide-up',
    animSpeed: 220,
  },
  elegant: {
    name: 'Elegant',
    fontFamily: 'Poppins',
    fontSize: 66,
    bold: false,
    italic: true,
    uppercase: false,
    textColor: '#FFEFD5',
    outlineColor: '#2C1810',
    shadowColor: '#1A0F0A',
    outline: 3,
    shadow: 3,
    glow: 7,
    glowColor: '#FFD700',
    sentenceAnimation: 'fade-in',
    animSpeed: 420,
  },
  goldenhour: {
    name: 'Golden Hour',
    fontFamily: 'Montserrat',
    fontSize: 70,
    bold: true,
    italic: false,
    uppercase: false,
    textColor: '#FFD700',
    outlineColor: '#7A3B00',
    shadowColor: '#3D1C00',
    outline: 4,
    shadow: 5,
    glow: 10,
    glowColor: '#FFA500',
    sentenceAnimation: 'fade-in',
    animSpeed: 360,
  },
  icecold: {
    name: 'Ice Cold',
    fontFamily: 'Bebas Neue',
    fontSize: 74,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#A8EDFF',
    outlineColor: '#003E5C',
    shadowColor: '#001A26',
    outline: 3,
    shadow: 5,
    glow: 14,
    glowColor: '#A8EDFF',
    sentenceAnimation: 'slide-up',
    animSpeed: 270,
  },
  boldstrike: {
    name: 'Bold Strike',
    fontFamily: 'Anton',
    fontSize: 82,
    bold: true,
    italic: false,
    uppercase: true,
    textColor: '#FFFF00',
    outlineColor: '#000000',
    shadowColor: '#111111',
    outline: 6,
    shadow: 4,
    glow: 6,
    glowColor: '#FFFF00',
    sentenceAnimation: 'slide-up',
    animSpeed: 195,
  },
};
